-- One-time seed for the English Vocabulary word list, imported verbatim from
-- an existing notes-app list. Run this ONCE in the Supabase SQL editor, after
-- schema.sql (which creates the vocab_words table). Safe to re-run by
-- accident — it no-ops if vocab_words already has any rows.
--
-- Definitions are copied exactly as given; words without one are `null` and
-- can be filled in later from the English Vocabulary screen in the app.

do $$
begin
  if not exists (select 1 from public.vocab_words) then
    insert into public.vocab_words (id, user_id, word, definition)
    select 'vocab_' || gen_random_uuid()::text, (select id from auth.users limit 1), word, definition
    from (values
    ('Cynical', 'motivated by self interest'),
    ('Veramin', 'pests or animals that destroy livestock or property'),
    ('Voluptuary', 'someone who''s main focus is luxury'),
    ('Sensuality', 'relating to the senses'),
    ('Dredge', 'to dig or gather'),
    ('Diaphanous', 'very fine fabric or delicate / vague'),
    ('Obstinacy', 'stubbornness'),
    ('Regiment', 'orderly'),
    ('Reticence', 'inclined to be silent'),
    ('Elude', 'avoid'),
    ('Convulsion', 'contractions of the muscle'),
    ('Vestibule', 'a passage or hall outside a building'),
    ('Uncanny', 'strange or mysterious in an unsettling way'),
    ('Venerated', 'to honor'),
    ('Aridity', 'dryness'),
    ('Ephemeral', 'lasting a very short time/ not permanent'),
    ('Coagulating', 'to thicken, or form into group'),
    ('Mysticism', 'the belief that people can directly experience God or true reality'),
    ('Dissonance', 'an inconsistency / difference'),
    ('Misanthrope', 'someone who hates mankind'),
    ('Repugnant', 'hostile towards someone'),
    ('Archaic', 'no longer used'),
    ('Resentful', 'dislike'),
    ('Resuscitate', 'to bring back to consciousness or revive'),
    ('Vacillating', 'fluctuate between things'),
    ('Vehemance', 'passion'),
    ('Indignation', 'justified anger'),
    ('Elopement', 'to slip away'),
    ('Invigorating', 'something that gives you mental energy'),
    ('Penury', 'severe poverty'),
    ('Conflagration', 'conflict ,war, or a disastrous fire'),
    ('Ineptitude', 'not being suited/ incapable'),
    ('Piety', 'divine and worshipping'),
    ('Capricious', 'impulsive/unpredictable'),
    ('Dolorous', 'grief or misery'),
    ('Fatuous', 'foolish'),
    ('Fraudulent', 'fraud'),
    ('Consternation', 'so amazed you become confused'),
    ('Preposterously', 'absurd'),
    ('Surreptitiously', 'something acquired secretly'),
    ('Clandestine', 'done in secrecy'),
    ('Presumptuous', 'presume'),
    ('Pertinacious', 'persistent to an opinion'),
    ('Eccentricity', 'your own odd ways'),
    ('Mahogany', 'type of wood'),
    ('Hypochondriac', 'someone paranoid about sicknesses'),
    ('Pragmatic', 'practical'),
    ('Pastoralism', 'to do with farming or shepherding'),
    ('Perfunctory', 'lacking in interest or enthusiasm'),
    ('Spinsterish', 'unmarried old woman'),
    ('Indelible', 'hard to remove, long lasting'),
    ('Propitious', 'good chance / favorable'),
    ('Lascivious', 'feeling or showing sexual desire in an offensive way'),
    ('Peremptory', 'insisting on immediate attention or obedience ( to someones actions or manners)'),
    ('Finagle', 'obtain something through devious or dishonest means'),
    ('Vociferous', 'express feelings in a loud or forceful way'),
    ('Forlorn', 'pitifully sad, abandoned or lonely'),
    ('Omniscient', 'knowing everything'),
    ('Pious', 'devotedly religious'),
    ('Dilapidated', 'precipitated into a state of ruin because of neglect or misuse'),
    ('Luminous', 'bright/ shining, especially in the dark'),
    ('Placid', 'not easily upset or excited'),
    ('Sombre', 'gloomy, lack of tone'),
    ('Lurid', 'very vivid in color to create harsh or unpleasant effect'),
    ('Sedentary', 'inactive, sitting a lot'),
    ('Legionaries', 'roman soldiers'),
    ('Witted', 'inteligent, perceptive, clever'),
    ('Sepulcher', 'tomb'),
    ('Gaberdine', 'cloak'),
    ('Imperturbably', 'unexcitedly, calm'),
    ('Erroneous', 'containing mistakes, incorrect'),
    ('Emissary', 'a person sent on a special mission'),
    ('Languid', 'showing little energy in movements'),
    ('Lugubrious', 'looking or sounding sad and dismal'),
    ('Drollery', 'whimsically amusing or funny'),
    ('Morose', 'gloomy'),
    ('Declivity', 'downward slope'),
    ('Uncongenial', 'unfriendly'),
    ('Malaprop', 'mistaking a word for a similar word in an amusing way or by accident'),
    ('Pestilence', 'deadly disease'),
    ('Verily', 'certainly'),
    ('Languidly', 'weakly'),
    ('Assegais', 'a spear used by southern african people'),
    ('Sepulchral', 'relating to a tomb or funeral'),
    ('Impregnable', 'unable to be captured or broken into'),
    ('Impetuous', 'done quickly without thought or care'),
    ('Pestilential', 'deadly; poisonous; contagious'),
    ('Rudimentary', 'elementary / basic level'),
    ('Apparition', 'a ghost'),
    ('Imbecile', 'a stupid person'),
    ('Solace', 'comfort in a time of distress or sadness'),
    ('Convulsively', null),
    ('Tenebrous', null),
    ('Lofty', null),
    ('Serene', null),
    ('Impalpable', null),
    ('Convulsions', null),
    ('Banal', null),
    ('Antithesis', null),
    ('Contingent', 'subject to change'),
    ('Feigned', null),
    ('Futility', null),
    ('Lampoonery', null),
    ('Pernicious', null),
    ('Vocational', 'relating to an occupation or employment.'),
    ('Edifice', null),
    ('Apathy', 'lack of interest, enthusiasm, concern'),
    ('Conglomerate', 'different things grouped together to create a whole, but still with distinct entities'),
    ('Superimposed', 'to place on top of something, layered'),
    ('Exorbitant', 'unreasonably high price or amount charged'),
    ('Predilection', 'a bias, or preference for something'),
    ('Vicissitudes', null),
    ('Cognizant', 'to be aware of, or informed'),
    ('Vindicated', 'show or proven to be right / justified'),
    ('Gregarious', 'social'),
    ('Ephemeral', 'lasting for a short time'),
    ('Colloquial', 'informal language used in ordinary conversation (slang)'),
    ('Pernicious', 'having a toxic effect in a subtle or gradual way'),
    ('Nobility', null),
    ('Ostensibly', null),
    ('Usurpations', 'taking control of something without having the authority to do so'),
    ('Facetious', 'being sarcastic to serious issues'),
    ('Myriad', 'countless or extremely great number'),
    ('Convoluted', 'argument or story that is hard to follow'),
    ('Diaspora', 'the spread of people from their original homeland'),
    ('Harrowing', null),
    ('Despondency', 'low spirit caused by loss of hope'),
    ('Disavowel', 'denial of support or connection to something or someone'),
    ('Similitude', 'quality of being similar'),
    ('Divergence', 'seperation'),
    ('Mundane', 'lacking excitement , dull'),
    ('Vicariously', 'experiencing in imagination through the actions of another person'),
    ('Exulansis', 'giving up talking about something because people can''t relate'),
    ('Unyielding', 'not giving way to pressure, hard/solid'),
    ('Ersatz', 'a inferior replica'),
    ('Languorous', 'tiredness, but a good kind (like during a pickle ball match)'),
    ('Incessantly', 'constantly / without interruption'),
    ('Congenial', 'pleasant due to personality'),
    ('Gaudy', 'so bright and showing that it''s kinda tasteless'),
    ('Opulence', null),
    ('Lament', 'a passionate expression of grief and sorrow'),
    ('Acquiesce', 'agree without protest'),
    ('Laboriously', 'in a manner that takes time and effort'),
    ('Capriciously', null),
    ('Fretful', 'worrisome'),
    ('Contrive', null),
    ('Jarring', null),
    ('Conviviality', null),
    ('Fruitful', null),
    ('Serendipity', 'finding something good without looking for it'),
    ('Celestial', null),
    ('Fallacy', null),
    ('Adroit', 'clever or skillful in the use of hands of mind'),
    ('Insolent', 'arrogant and lack of respect to someone you should respect'),
    ('Poised', 'composure and self assured manner'),
    ('Genial', 'friendly or cheerful'),
    ('Assuage', null),
    ('Incongruous', null),
    ('Feasible', 'possible to do easily or conveniently'),
    ('Unprecedented', 'never known or done before'),
    ('Polygamist', 'someone who has more than one spouse at the same time'),
    ('Delirium', null),
    ('Sacrosanct', null),
    ('Subliminal', 'unconscious'),
    ('Ineradicable', null),
    ('Mahogany', null),
    ('Stoic', 'a person who can endure hardship without showing their feelings or complaining'),
    ('Endemic', null),
    ('Ostensibly', 'apparently'),
    ('Calamity', 'a disaster'),
    ('Gilded', null),
    ('Grim', 'uninviting'),
    ('Futility', null),
    ('Innocuous', 'not harmful or offensive'),
    ('Resplendent', null),
    ('Imperviously', 'not influenced or affected by something'),
    ('Equanimity', 'composure'),
    ('Warily', null),
    ('Presbyterian', 'relating to Christianity'),
    ('Malaise', 'general feeling of discomfort or illness'),
    ('Banal', 'so unoriginal it''s boring'),
    ('Altruism', 'unselfish'),
    ('Turmoil', 'a state of disturbance, confusion, or uncertainty'),
    ('Effeminate', 'acting with feminine qualities'),
    ('Incongruous', 'out of place, inappropriate'),
    ('Unscrupulous', 'not fair or honest, no morals'),
    ('Sprawl', 'sit or lie in a relaxed careless position; legs spread out'),
    ('Seer', 'a person who can supposedly see into the future through supernatural insight'),
    ('Malign', null),
    ('Fickleness', 'changeability - regarding actions or beliefs of feelings'),
    ('Demise', 'death or end'),
    ('Akin', 'of similar character'),
    ('Scorn', 'feeling that someone or something is not worthy of respect or approval'),
    ('Portent', 'a warning that something, momentous or calamitous is going to happen, or an exceptional or wonderful person or thing'),
    ('Hyperborean', 'relating to the extreme north'),
    ('obstreperous', 'noisy and difficult to control (like drunkards)'),
    ('Prodigious', 'remarkably great in size or length'),
    ('Eschewed', 'abstain from'),
    ('solemnity', 'the state or quality of being dignified or serious'),
    ('Paragon', 'a person or thing regarded as a perfect example of a particular quality'),
    ('Pagon', 'holding beliefs other than that of a main religion'),
    ('Perspicacious', 'having ready insight and understanding of things'),
    ('Caustic', 'sarcastic in a bitter and critical way'),
    ('Scathing', 'severely critical'),
    ('Contempt', 'disregard for something that should be taken into account.'),
    ('Radical', 'affecting the fundamental nature of something; far reaching; thorough'),
    ('Cathartic', 'providing psychological relief through the open expression of emotion.'),
    ('Portentous', 'being more serious than necessary to impress people'),
    ('Tumultuous', null),
    ('Tonic', 'invigorating'),
    ('Ostentatious', 'vulgar or pretentious display in attempt to impress or attract attention'),
    ('Humdrum', 'monotonous, dull, boring'),
    ('Confabulations', null),
    ('Rapacious', 'aggressively greedy'),
    ('Vitiate', 'spoil or impair the quality of'),
    ('Descried', 'to catch sight of'),
    ('Indisposed', 'slightly unwell'),
    ('Detestable', 'deserving intense dislike'),
    ('Debased', 'reduced in quality or value'),
    ('Abase', 'behave in a way that degrades or belittles'),
    ('Corporeal', 'relating to a person''s body, especially as opposed to the body'),
    ('Agnosticism', 'neither believing or disbelieving in the existence of a god'),
    ('Platonism', null),
    ('Miltonic', 'Grand, majestic, style, biblical allusions and profound philosophical depth'),
    ('Egalitarian', 'the principal that all people are equal and deserve equal opportunity and rights'),
    ('Pantheistic', 'divine is present in all of reality, universe, nature, and reality are the same as a supreme entity'),
    ('Conviction', 'a firmly held belief or opinion'),
    ('Effeminacy', 'have feminine traits a man, negative connotation'),
    ('Solipsism', 'thinking that ur mind is the only one, everyone is ur consciousness'),
    ('Anthropomorphize', 'attributing human characteristics to a god, animal, or object'),
    ('Tacit', 'understood or implied without being stated'),
    ('Mutineer', 'a soldier or sailor who refuses to obey orders of the captain'),
    ('Advert', 'an advertisement'),
    ('Prudent', 'acting with and showing care for the future'),
    ('Assailable', 'open to attack'),
    ('Incongruous', 'not in harmony with the surroundings'),
    ('Alluring', 'powerfully and mysteriously attracting and fascinating'),
    ('Polarity', 'divide or cause to divide into two sharply contrasting groups or set of beliefs'),
    ('Kinship', 'relating to blood, marital, or familial relationships'),
    ('Assuage', 'make an unpleasant feeling less intense'),
    ('Anomalous', 'anomaly —> deriving from what is expected or standard'),
    ('Indomitable', 'impossible to defeat or subdue'),
    ('Subdue', 'overcome or bring under control'),
    ('Palpable', 'so intense it feels tangible'),
    ('Dehiscent', 'characterized by splitting or bursting open'),
    ('Iconoclasm', 'the action of criticizing or attacking cherished beliefs'),
    ('Hubristic', 'excessively proud or self-confident'),
    ('Voodoo', 'magical, religious, sorcerous'),
    ('Upending', 'turning something on its end or upside down'),
    ('Gallantly', 'in a brave or heroic manner; charmingly chivalrous manner'),
    ('Fallible', 'capable of making mistakes or being erroneous'),
    ('Poised', 'composed'),
    ('Jest', null),
    ('Invidious', 'likely to evoke resentment or anger from others'),
    ('flâneur', 'a French term describing a person who walks around a city without any purpose, observing the people around him'),
    ('Prolific', 'plentiful, fruitful, in'),
    ('inquietude', 'physical or mental restlessness'),
    ('Maudlin', 'self-pityingly or tearfully sentimental, often through drunkness'),
    ('Avarice', 'extreme greed for wealth or material gain'),
    ('Elysium', 'an eternal paradise in greek mythology - only for heroes and those sent by gods'),
    ('Lacerated', 'torn or deeply cut'),
    ('Acumen', null),
    ('Embargo', 'an official ban on trade or other commercial activity with a particular country'),
    ('Fastidious', 'very attentive and concerned about accuracy or detail'),
    ('Perverse', 'showing a deliberate and stubborn desire to act in an unreasonable or unacceptable way'),
    ('Extravagance', 'lacking restraint in spending money or resources'),
    ('Stringent', 'strict, precise'),
    ('Pandemonium', 'uproar, loud and noisy disorder or confusion'),
    ('Parse', 'analyze a sentence into its parts'),
    ('Cognitive dissonance', 'discomforting feeling when a person has conflicting beliefs or values'),
    ('Defacto', 'in effect, in fact, whether by right or not'),
    ('Flowery', 'full of full of elaborate or literary words and phrases'),
    ('Epistemology', 'theory of knowledge'),
    ('Prose', 'written or spoken language in its ordinary form'),
    ('Aberration', 'a departure from what is welcomed, typically one that is unwelcomed'),
    ('Vainglorious', null),
    ('Prosaic', null),
    ('Homage', null),
    ('Cynosure', null),
    ('Prepossessing', null),
    ('Martial', null),
    ('Analogous', null),
    ('lackadaisical', 'lacking enthusiasm or determination; carelessly lazy'),
    ('Gallantry', 'courageous behavior'),
    ('Forthcoming', null),
    ('Tonic', null),
    ('Disquietude', 'state of anxiousness or uneasiness'),
    ('Vain', 'having or showing high opinion of one''s opinion or worth'),
    ('Rapt', 'completely fascinated by what someone is seeing or hearing'),
    ('Benign', 'not harmful'),
    ('Vapid', 'not stimulating or challenging'),
    ('Taciturn', 'saying little, reserved'),
    ('Tacit', 'implied without saying anything'),
    ('Stolidly', 'calm, dependable, showing little emotion'),
    ('Unassailable', 'unable to be attacked, questioned, or defeated'),
    ('Brazen', 'bold and without shame'),
    ('Ravenous', 'extremely hungry'),
    ('Voracious', 'wanting or devouring great quantities of something'),
    ('Nullify', 'to invalidate'),
    ('Nullity', 'something of no importance or worth'),
    ('Ceaseless', 'constant and unending'),
    ('Cease', 'to bring to an end'),
    ('Sophistry', 'the use of fallacious arguments, usually to deceive'),
    ('Compunctions', 'feeling of unease or guilt about something done or contemplated, usually arising from moral consciousness'),
    ('Incandescence', 'emitting light due to being heated'),
    ('Apothecary', 'a person who prepared and sold medicine and drugs'),
    ('Enervating', 'exhausting or draining'),
    ('Covertly', 'secretly, displayed without knowledge'),
    ('Crescendo', 'the loudest point reached of a sound'),
    ('Conciliate', 'stop from being angry'),
    ('Pallid', 'pale bc of bad health'),
    ('Provision', 'supplying or providing something for use'),
    ('Potentate', 'a monarch or ruler'),
    ('Fornication', 'sex between 2 unmarried people'),
    ('Primordial', null),
    ('Salient', null),
    ('Presuppose', null),
    ('Perennial', 'lasting for long or infinite times'),
    ('psychosomatic', 'caused by mental factor like stress or internal conflict (coming from the mind)'),
    ('Panpsychism', null),
    ('Pantomime', null),
    ('Fable', null),
    ('Eminent', null),
    ('Gaiety', null),
    ('Septic', null),
    ('Tortuous', null)
    ) as v(word, definition);
  end if;
end $$;
