// Urdu flashcard data (Elementary Urdu II). Generated from the handoff spec.
// Do not hand-edit ids; `mastered` state is keyed on them.

export type UrduCard = { id: string; urdu: string; english: string; roman: string; cat: string };

export const URDU_CATEGORIES = ["All", "Vocab", "Weather", "Fruits", "Vegetables", "Adjectives", "Colors", "Verbs", "Phrases"] as const;

export const URDU_CARDS: UrduCard[] = [
  { id: "v1", urdu: "کمرہ", english: "Room", roman: "kamra", cat: "Vocab" },
  { id: "v2", urdu: "میز", english: "Table", roman: "mez", cat: "Vocab" },
  { id: "v3", urdu: "کرسی", english: "Chair", roman: "kursi", cat: "Vocab" },
  { id: "v4", urdu: "صوفہ", english: "Sofa", roman: "sofa", cat: "Vocab" },
  { id: "v5", urdu: "قالین", english: "Carpet", roman: "qaleen", cat: "Vocab" },
  { id: "v6", urdu: "کتاب", english: "Book", roman: "kitaab", cat: "Vocab" },
  { id: "v7", urdu: "دروازہ", english: "Door", roman: "darwaza", cat: "Vocab" },
  { id: "v8", urdu: "کھڑکی", english: "Window", roman: "khirki", cat: "Vocab" },
  { id: "v9", urdu: "الماری", english: "Cupboard", roman: "almaari", cat: "Vocab" },
  { id: "v10", urdu: "خط", english: "Letter", roman: "khat", cat: "Vocab" },
  { id: "v11", urdu: "پنسل", english: "Pencil", roman: "pensil", cat: "Vocab" },
  { id: "v12", urdu: "سوال", english: "Question", roman: "sawal", cat: "Vocab" },
  { id: "v13", urdu: "گھر", english: "House / Home", roman: "ghar", cat: "Vocab" },
  { id: "v14", urdu: "باغ", english: "Garden", roman: "baagh", cat: "Vocab" },
  { id: "v15", urdu: "گائوں", english: "Village", roman: "gaon", cat: "Vocab" },
  { id: "v16", urdu: "کھیت", english: "Field", roman: "khet", cat: "Vocab" },
  { id: "v17", urdu: "باورچی خانہ", english: "Kitchen", roman: "bawarchi khana", cat: "Vocab" },
  { id: "v18", urdu: "درخت", english: "Tree", roman: "darakht", cat: "Vocab" },
  { id: "v19", urdu: "دال", english: "Lentils", roman: "daal", cat: "Vocab" },
  { id: "v20", urdu: "کہانی", english: "Story", roman: "kahaani", cat: "Vocab" },
  { id: "w1", urdu: "موسم", english: "Weather / Season", roman: "mausam", cat: "Weather" },
  { id: "w2", urdu: "صبح", english: "Morning", roman: "subah", cat: "Weather" },
  { id: "w3", urdu: "دوپہر", english: "Afternoon", roman: "dopahar", cat: "Weather" },
  { id: "w4", urdu: "شام", english: "Evening", roman: "shaam", cat: "Weather" },
  { id: "w5", urdu: "رات", english: "Night", roman: "raat", cat: "Weather" },
  { id: "w6", urdu: "دن", english: "Day", roman: "din", cat: "Weather" },
  { id: "w7", urdu: "گرمیاں", english: "Summer", roman: "garmiyan", cat: "Weather" },
  { id: "w8", urdu: "سردیاں", english: "Winter", roman: "sardiyan", cat: "Weather" },
  { id: "w9", urdu: "خزاں", english: "Autumn", roman: "khazaan", cat: "Weather" },
  { id: "w10", urdu: "بارش", english: "Rain", roman: "baarish", cat: "Weather" },
  { id: "w11", urdu: "برف", english: "Snow", roman: "barf", cat: "Weather" },
  { id: "w12", urdu: "بادل", english: "Cloud", roman: "baadal", cat: "Weather" },
  { id: "w13", urdu: "آسمان", english: "Sky", roman: "aasmaan", cat: "Weather" },
  { id: "w14", urdu: "سورج", english: "Sun", roman: "suraj", cat: "Weather" },
  { id: "w15", urdu: "چاند", english: "Moon", roman: "chaand", cat: "Weather" },
  { id: "w16", urdu: "ستارے", english: "Stars", roman: "sitaare", cat: "Weather" },
  { id: "w17", urdu: "دھوپ", english: "Sunshine", roman: "dhoop", cat: "Weather" },
  { id: "w18", urdu: "ہوا", english: "Wind / Air", roman: "hawa", cat: "Weather" },
  { id: "f1", urdu: "آم", english: "Mango", roman: "aam", cat: "Fruits" },
  { id: "f2", urdu: "مالٹا", english: "Orange", roman: "maalta", cat: "Fruits" },
  { id: "f3", urdu: "کیلا", english: "Banana", roman: "kela", cat: "Fruits" },
  { id: "f4", urdu: "سیب", english: "Apple", roman: "seb", cat: "Fruits" },
  { id: "f5", urdu: "انگور", english: "Grapes", roman: "angoor", cat: "Fruits" },
  { id: "f6", urdu: "ناشپاتی", english: "Pear", roman: "naashpaati", cat: "Fruits" },
  { id: "f7", urdu: "خربوزہ", english: "Melon", roman: "kharboza", cat: "Fruits" },
  { id: "f8", urdu: "سٹرابیری", english: "Strawberry", roman: "strawberry", cat: "Fruits" },
  { id: "vg1", urdu: "ٹماٹر", english: "Tomato", roman: "tamaatar", cat: "Vegetables" },
  { id: "vg2", urdu: "پالک", english: "Spinach", roman: "paalak", cat: "Vegetables" },
  { id: "vg3", urdu: "گاجر", english: "Carrot", roman: "gajar", cat: "Vegetables" },
  { id: "vg4", urdu: "بھنڈی", english: "Okra", roman: "bhindi", cat: "Vegetables" },
  { id: "vg5", urdu: "کھیرا", english: "Cucumber", roman: "kheera", cat: "Vegetables" },
  { id: "vg6", urdu: "مٹر", english: "Peas", roman: "matar", cat: "Vegetables" },
  { id: "vg7", urdu: "گوبھی", english: "Cauliflower", roman: "gobhi", cat: "Vegetables" },
  { id: "a1", urdu: "اچھا", english: "Good", roman: "achha", cat: "Adjectives" },
  { id: "a2", urdu: "بڑا", english: "Big / Tall", roman: "bara", cat: "Adjectives" },
  { id: "a3", urdu: "چھوٹا", english: "Small", roman: "chhota", cat: "Adjectives" },
  { id: "a4", urdu: "لمبا", english: "Long / Tall", roman: "lamba", cat: "Adjectives" },
  { id: "a5", urdu: "خوبصورت", english: "Beautiful", roman: "khubsurat", cat: "Adjectives" },
  { id: "a6", urdu: "مشکل", english: "Difficult", roman: "mushkil", cat: "Adjectives" },
  { id: "a7", urdu: "آسان", english: "Easy", roman: "aasaan", cat: "Adjectives" },
  { id: "a8", urdu: "میٹھا", english: "Sweet", roman: "meetha", cat: "Adjectives" },
  { id: "a9", urdu: "کھٹا", english: "Sour", roman: "khatta", cat: "Adjectives" },
  { id: "a10", urdu: "کڑوا", english: "Bitter", roman: "karwa", cat: "Adjectives" },
  { id: "a11", urdu: "مزیدار", english: "Delicious", roman: "mazedaar", cat: "Adjectives" },
  { id: "a12", urdu: "گرم", english: "Hot / Warm", roman: "garm", cat: "Adjectives" },
  { id: "a13", urdu: "ٹھنڈا", english: "Cold", roman: "thanda", cat: "Adjectives" },
  { id: "a14", urdu: "خوش", english: "Happy", roman: "khush", cat: "Adjectives" },
  { id: "a15", urdu: "اداس", english: "Sad", roman: "udaas", cat: "Adjectives" },
  { id: "a16", urdu: "صاف", english: "Clean", roman: "saaf", cat: "Adjectives" },
  { id: "c1", urdu: "لال", english: "Red", roman: "laal", cat: "Colors" },
  { id: "c2", urdu: "پیلا", english: "Yellow", roman: "peela", cat: "Colors" },
  { id: "c3", urdu: "ہرا", english: "Green", roman: "hara", cat: "Colors" },
  { id: "c4", urdu: "نیلا", english: "Blue", roman: "neela", cat: "Colors" },
  { id: "c5", urdu: "سفید", english: "White", roman: "safed", cat: "Colors" },
  { id: "c6", urdu: "کالا", english: "Black", roman: "kaala", cat: "Colors" },
  { id: "c7", urdu: "جامنی", english: "Purple", roman: "jaamni", cat: "Colors" },
  { id: "c8", urdu: "بھورا", english: "Brown", roman: "bhoora", cat: "Colors" },
  { id: "c9", urdu: "سرخ", english: "Crimson / Red", roman: "surkh", cat: "Colors" },
  { id: "vb1", urdu: "کھانا", english: "To eat", roman: "khaana", cat: "Verbs" },
  { id: "vb2", urdu: "پینا", english: "To drink", roman: "peena", cat: "Verbs" },
  { id: "vb3", urdu: "پکانا", english: "To cook", roman: "pakaana", cat: "Verbs" },
  { id: "vb4", urdu: "پڑھنا", english: "To read / study", roman: "parhna", cat: "Verbs" },
  { id: "vb5", urdu: "لکھنا", english: "To write", roman: "likhna", cat: "Verbs" },
  { id: "vb6", urdu: "دیکھنا", english: "To see / look", roman: "dekhna", cat: "Verbs" },
  { id: "vb7", urdu: "سننا", english: "To listen / hear", roman: "sunna", cat: "Verbs" },
  { id: "vb8", urdu: "سمجھنا", english: "To understand", roman: "samajhna", cat: "Verbs" },
  { id: "vb9", urdu: "سمجھانا", english: "To explain", roman: "samjhaana", cat: "Verbs" },
  { id: "vb10", urdu: "جانا", english: "To go", roman: "jaana", cat: "Verbs" },
  { id: "vb11", urdu: "آنا", english: "To come", roman: "aana", cat: "Verbs" },
  { id: "vb12", urdu: "سونا", english: "To sleep", roman: "sona", cat: "Verbs" },
  { id: "vb13", urdu: "اٹھنا", english: "To get up / rise", roman: "uthna", cat: "Verbs" },
  { id: "vb14", urdu: "بیٹھنا", english: "To sit", roman: "baithna", cat: "Verbs" },
  { id: "vb15", urdu: "کھولنا", english: "To open", roman: "kholna", cat: "Verbs" },
  { id: "vb16", urdu: "رکھنا", english: "To keep / put", roman: "rakhna", cat: "Verbs" },
  { id: "vb17", urdu: "پوچھنا", english: "To ask", roman: "poochna", cat: "Verbs" },
  { id: "vb18", urdu: "ناچنا", english: "To dance", roman: "naachna", cat: "Verbs" },
  { id: "vb19", urdu: "ہنسنا", english: "To laugh", roman: "hansna", cat: "Verbs" },
  { id: "vb20", urdu: "کھیلنا", english: "To play", roman: "khelna", cat: "Verbs" },
  { id: "vb21", urdu: "بھاگنا", english: "To run", roman: "bhaagna", cat: "Verbs" },
  { id: "vb22", urdu: "رونا", english: "To cry", roman: "rona", cat: "Verbs" },
  { id: "p1", urdu: "آج بہت گرمی ہے", english: "It is very hot today", roman: "aaj bahut garmi hai", cat: "Phrases" },
  { id: "p2", urdu: "مجھے پیاس لگی ہے", english: "I am thirsty", roman: "mujhe pyaas lagi hai", cat: "Phrases" },
  { id: "p3", urdu: "کیا خبر ہے؟", english: "What is the news?", roman: "kya khabar hai?", cat: "Phrases" },
  { id: "p4", urdu: "یہ کیا ہے؟", english: "What is this?", roman: "yeh kya hai?", cat: "Phrases" },
  { id: "p5", urdu: "وہ کون ہے؟", english: "Who is that?", roman: "woh kaun hai?", cat: "Phrases" },
  { id: "p6", urdu: "تم کہاں رہتے ہو؟", english: "Where do you live?", roman: "tum kahan rehte ho?", cat: "Phrases" },
  { id: "p7", urdu: "بہت اچھا", english: "Very good", roman: "bahut achha", cat: "Phrases" },
  { id: "p8", urdu: "خوشی خوشی", english: "Happily", roman: "khushi khushi", cat: "Phrases" },
];
